// Owner-approved Phase 0.8 seed contract, revision 1.
// This is a backend-owned artifact, never a runtime import of frontend fixtures.
// Import/apply and legacy reconciliation remain separate explicit operations.
export interface MasterSeedDefinition {
  readonly code: string;
  readonly name: string;
  readonly description: string;
  readonly allowTenantCreate: boolean;
  readonly allowTenantEdit: boolean;
  readonly allowTenantDeactivate: boolean;
  readonly allowIndustryDefaults: boolean;
  readonly systemValuePolicy: "OVERRIDABLE_LABEL" | "LOCKED_IDENTITY";
  readonly moduleCode: string | null;
  readonly metadataSchema: "NONE";
  readonly valueType: "LABEL";
  readonly status: "ACTIVE";
  readonly displayOrder: number;
}
export interface MasterSeedValue {
  readonly definitionCode: string;
  readonly code: string;
  readonly name: string;
  readonly description: string;
  readonly source: "SYSTEM";
  readonly tenantId: null;
  readonly industryTemplateVersionId: null;
  readonly displayColor: string | null;
  readonly sortOrder: number;
  readonly isActive: boolean;
}
export const MASTER_SEED_PROVENANCE = {
  contractRevision: 1,
  approvedBaseline: "8709198fecd4e180b21358138eb5708d509c106d",
  fixtureGitBlobSha256:
    "831fb902b1231329dbb072c0b1de8e5a988865acf5ddc93d2b74a65c4421c80b",
  classificationGitBlobSha256:
    "142b8875ffc51d82f60a9cf6158c98784320cf22ebc488f7e9f1781819fff6de",
  expectedDefinitionCount: 24,
  expectedSystemValueCount: 44,
} as const;

export const MASTER_SEED_DEFINITIONS: readonly MasterSeedDefinition[] = [
  {
    code: "designation",
    name: "Designations",
    description: "Selectable organization role titles.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: null,
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 1,
  },
  {
    code: "contact_role",
    name: "Contact roles",
    description: "Selectable roles for business contacts.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 2,
  },
  {
    code: "leave_type",
    name: "Leave types",
    description: "Selectable leave and duty category labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "attendance",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 3,
  },
  {
    code: "followup_type",
    name: "Follow-up types",
    description: "Selectable follow-up interaction categories.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 4,
  },
  {
    code: "followup_outcome",
    name: "Follow-up outcomes",
    description: "Selectable reported outcomes of follow-up interactions.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 5,
  },
  {
    code: "demo_type",
    name: "Demo types",
    description: "Selectable product demonstration formats.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "demo_scheduler",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 6,
  },
  {
    code: "task_activity_type",
    name: "Task and activity types",
    description: "Selectable task and activity categories.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 7,
  },
  {
    code: "lead_source",
    name: "Lead sources",
    description: "Selectable lead acquisition channels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 8,
  },
  {
    code: "lost_reason",
    name: "Lost deal reasons",
    description: "Selectable reported reasons for a lost opportunity.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 9,
  },
  {
    code: "visit_type",
    name: "Visit types",
    description: "Selectable field visit categories.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "field_visits",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 10,
  },
  {
    code: "visit_reason",
    name: "Visit cancellation reasons",
    description:
      "Selectable reported reasons for a cancelled or rescheduled visit.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "field_visits",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 11,
  },
  {
    code: "expense_category",
    name: "Expense categories",
    description: "Selectable expense classification labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: null,
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 12,
  },
  {
    code: "business_type",
    name: "Business categories",
    description: "Selectable business category labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 13,
  },
  {
    code: "incentive_type",
    name: "Incentive types",
    description: "Selectable incentive or award head labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "payroll",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 14,
  },
  {
    code: "allowance_type",
    name: "Allowance types",
    description: "Selectable allowance head labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "payroll",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 15,
  },
  {
    code: "deduction_type",
    name: "Deduction types",
    description: "Selectable deduction head labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "payroll",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 16,
  },
  {
    code: "skill_set",
    name: "Skills",
    description: "Selectable skill labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: null,
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 17,
  },
  {
    code: "document_type",
    name: "Document types",
    description: "Selectable document category labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: null,
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 18,
  },
  {
    code: "deal_priority",
    name: "Deal priorities",
    description: "Selectable priority labels for opportunities.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 19,
  },
  {
    code: "competitor_brand",
    name: "Competitor brands",
    description: "Selectable competitor brand labels.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "core_crm",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 20,
  },
  {
    code: "demo_failure_reason",
    name: "Demo failure reasons",
    description:
      "Selectable reported reasons a demonstration could not proceed.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "demo_scheduler",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 21,
  },
  {
    code: "visit_objective",
    name: "Visit objectives",
    description: "Selectable objectives for a field visit.",
    allowTenantCreate: true,
    allowTenantEdit: true,
    allowTenantDeactivate: true,
    allowIndustryDefaults: true,
    systemValuePolicy: "OVERRIDABLE_LABEL",
    moduleCode: "field_visits",
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 22,
  },
  {
    code: "target_metric_type",
    name: "Target metric types",
    description:
      "Selectable stable metric labels without calculation semantics.",
    allowTenantCreate: false,
    allowTenantEdit: false,
    allowTenantDeactivate: false,
    allowIndustryDefaults: false,
    systemValuePolicy: "LOCKED_IDENTITY",
    moduleCode: null,
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 23,
  },
  {
    code: "target_type",
    name: "Target scope types",
    description: "Selectable stable target assignment-scope labels.",
    allowTenantCreate: false,
    allowTenantEdit: false,
    allowTenantDeactivate: false,
    allowIndustryDefaults: false,
    systemValuePolicy: "LOCKED_IDENTITY",
    moduleCode: null,
    metadataSchema: "NONE",
    valueType: "LABEL",
    status: "ACTIVE",
    displayOrder: 24,
  },
];
export const MASTER_SEED_VALUES: readonly MasterSeedValue[] = [
  {
    definitionCode: "contact_role",
    code: "OWNER",
    name: "Owner / Proprietor",
    description: "Business owner or proprietor contact role.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#7C3AED",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "contact_role",
    code: "MANAGER",
    name: "Store Manager",
    description: "Store management contact role.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "contact_role",
    code: "OPS_HEAD",
    name: "Operations Head",
    description: "Operations leadership contact role.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#D97706",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "contact_role",
    code: "FINANCE",
    name: "Accountant / Finance",
    description: "Accounting or finance contact role.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#059669",
    sortOrder: 4,
    isActive: true,
  },
  {
    definitionCode: "followup_type",
    code: "QUOTE_FOLLOWUP",
    name: "Quotation Follow-up",
    description: "Follow-up concerning a quotation.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#7C3AED",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "followup_type",
    code: "DEMO_FOLLOWUP",
    name: "Demo Follow-up",
    description: "Follow-up concerning a product demonstration.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "followup_type",
    code: "INFO_FOLLOWUP",
    name: "Product Info Follow-up",
    description: "Follow-up concerning product information.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#059669",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "followup_type",
    code: "PAYMENT_FOLLOWUP",
    name: "Payment Follow-up",
    description: "Follow-up concerning a payment.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#D97706",
    sortOrder: 4,
    isActive: true,
  },
  {
    definitionCode: "followup_outcome",
    code: "SEND_QUOTE",
    name: "Interested - Send Quote",
    description: "A quotation was requested.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#10B981",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "followup_outcome",
    code: "DEMO_REQ",
    name: "Product Demo Requested",
    description: "A product demonstration was requested.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#3B82F6",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "followup_outcome",
    code: "RESCHEDULED",
    name: "Call Rescheduled",
    description: "A call was rescheduled.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#F59E0B",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "followup_outcome",
    code: "NOT_REACHABLE",
    name: "Not Reachable",
    description: "Contact could not be reached.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#EF4444",
    sortOrder: 4,
    isActive: true,
  },
  {
    definitionCode: "demo_type",
    code: "WALKTHROUGH",
    name: "Product Walkthrough",
    description: "Standard software feature demonstration.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "demo_type",
    code: "ONSITE_POC",
    name: "Onsite Live POC",
    description: "Onsite setup and live pilot demonstration.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#7C3AED",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "demo_type",
    code: "VIRTUAL_DEMO",
    name: "Virtual Video Demo",
    description: "Demonstration over a video call.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#059669",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "task_activity_type",
    code: "SITE_VISIT",
    name: "In-Person Site Visit",
    description: "In-person site visit activity.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "task_activity_type",
    code: "PHONE_CALL",
    name: "Outbound Phone Call",
    description: "Outbound telephone call activity.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#059669",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "task_activity_type",
    code: "BROADCAST",
    name: "WhatsApp / Email Broadcast",
    description: "Messaging or email broadcast activity.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#D97706",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "lead_source",
    code: "FIELD_VISIT",
    name: "Direct Field Visit",
    description: "Lead originating from a field visit.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "lead_source",
    code: "REFERRAL",
    name: "Partner / Referral",
    description: "Lead originating from a referral.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "lost_reason",
    code: "HIGH_PRICE",
    name: "Price / Budget Constraint",
    description: "Price or budget was the reported concern.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "lost_reason",
    code: "COMPETITOR",
    name: "Competitor Selected",
    description: "An alternative provider was selected.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "lost_reason",
    code: "UNRESPONSIVE",
    name: "Unresponsive Merchant",
    description: "Contact was unresponsive.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "visit_type",
    code: "SALES_PITCH",
    name: "Sales Pitch & Demo",
    description: "Visit for a sales presentation or demonstration.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "visit_type",
    code: "FOLLOW_UP",
    name: "Follow-up Consultation",
    description: "Visit for a follow-up consultation.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#F59E0B",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "visit_type",
    code: "COLLECTION",
    name: "Payment Collection",
    description: "Visit concerning payment collection.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#10B981",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "visit_reason",
    code: "OWNER_BUSY",
    name: "Merchant Owner Unavailable",
    description: "The merchant owner was unavailable.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "visit_reason",
    code: "CLIENT_RESCHEDULE",
    name: "Rescheduled by Client",
    description: "The client requested rescheduling.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "expense_category",
    code: "FUEL",
    name: "Fuel & Commute",
    description: "Field travel fuel expenses.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "expense_category",
    code: "CLIENT_MEET",
    name: "Client Lunch & Hospitality",
    description: "Client meeting or hospitality expenses.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: null,
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "deal_priority",
    code: "P0_URGENT",
    name: "Urgent (P0)",
    description: "Urgent priority.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#DC2626",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "deal_priority",
    code: "P1_HIGH",
    name: "High (P1)",
    description: "High priority.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#D97706",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "deal_priority",
    code: "P2_NORMAL",
    name: "Normal (P2)",
    description: "Normal priority.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "demo_failure_reason",
    code: "NET_OFFLINE",
    name: "Store Internet / Wi-Fi Offline",
    description: "Internet or Wi-Fi connectivity was unavailable.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#DC2626",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "demo_failure_reason",
    code: "OWNER_ABSENT",
    name: "Key Decision Maker Absent",
    description: "A key decision maker was absent.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#D97706",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "demo_failure_reason",
    code: "HW_INCOMPAT",
    name: "Hardware Incompatible",
    description: "Hardware was incompatible.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#6B7280",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "visit_objective",
    code: "FIRST_PITCH",
    name: "First Prospecting & Pitch",
    description: "Initial prospecting and presentation objective.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "visit_objective",
    code: "ONSITE_DEMO",
    name: "Onsite Product Demonstration",
    description: "Onsite product demonstration objective.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#7C3AED",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "visit_objective",
    code: "ONBOARDING",
    name: "Contract Signing & Onboarding",
    description: "Contract signing and onboarding objective.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#059669",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "target_metric_type",
    code: "VISITS_COUNT",
    name: "Completed Field Visits",
    description: "Field-visit count metric label.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "target_metric_type",
    code: "DEMOS_COUNT",
    name: "Demos Delivered",
    description: "Demonstration count metric label.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#7C3AED",
    sortOrder: 3,
    isActive: true,
  },
  {
    definitionCode: "target_type",
    code: "TEAM_SCOPE",
    name: "Team Target Cluster",
    description: "Team-level target scope label.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#7C3AED",
    sortOrder: 1,
    isActive: true,
  },
  {
    definitionCode: "target_type",
    code: "INDIVIDUAL_SCOPE",
    name: "Individual Executive Quota",
    description: "Individual-level target scope label.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#2563EB",
    sortOrder: 2,
    isActive: true,
  },
  {
    definitionCode: "target_type",
    code: "TERRITORY_SCOPE",
    name: "Territory Zone Target",
    description: "Territory-level target scope label.",
    source: "SYSTEM",
    tenantId: null,
    industryTemplateVersionId: null,
    displayColor: "#059669",
    sortOrder: 3,
    isActive: true,
  },
];
