import { Prisma } from "@prisma/client";
import { ownerSelect } from "./crm-select";
export const leadSelect = {
  id: true,
  tenantId: true,
  leadCode: true,
  kind: true,
  name: true,
  businessName: true,
  contactName: true,
  phone: true,
  email: true,
  website: true,
  addressLine1: true,
  addressLine2: true,
  city: true,
  state: true,
  postalCode: true,
  countryCode: true,
  description: true,
  estimatedValue: true,
  expectedClosingDate: true,
  nextFollowUpAt: true,
  nextActionNote: true,
  requirementNote: true,
  disqualificationReason: true,
  sourceValueId: true,
  status: true,
  priority: true,
  ownerMembershipId: true,
  assignedMembershipId: true,
  ownerMembership: { select: ownerSelect },
  assignedMembership: { select: ownerSelect },
  accountId: true,
  contactId: true,
  convertedAccountId: true,
  convertedContactId: true,
  convertedAt: true,
  convertedByMembershipId: true,
  revision: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.LeadSelect;
export type LeadRow = Prisma.LeadGetPayload<{ select: typeof leadSelect }>;
export const conversionSelect = {
  leadId: true,
  idempotencyKey: true,
  payloadHash: true,
  accountId: true,
  contactId: true,
  resultRevision: true,
  createdAt: true,
} satisfies Prisma.LeadConversionCommandSelect;
