export interface BusinessCategoryItem {
  id: string;
  name: string;
  code: string;
  parentCategory: string;
  businessesCount: number;
  status: 'Active' | 'Inactive' | 'Archived';
  sortOrder: number;
  createdOn: string;
  createdBy: string;
  iconName: string;
  description: string;
  sales: number;
  target: number;
  achievementPct: number;
  leads: number;
  conversions: number;
  activeExecutives: number;
  defaultTargetTemplate?: string;
  applicableFor?: ('Field Sales' | 'Telecalling' | 'Both')[];
  allowLeadAssignment?: boolean;
  allowBusinessCreation?: boolean;
  tags?: string[];
}

export const mockCategoriesList: BusinessCategoryItem[] = [
  {
    id: 'cat-1',
    name: 'Retail Business',
    code: 'RETAIL',
    parentCategory: '—',
    businessesCount: 1854,
    status: 'Active',
    sortOrder: 1,
    createdOn: '12 May 2025',
    createdBy: 'Rohit Sharma',
    iconName: 'ShoppingBag',
    description: 'Retail stores, supermarkets, grocery outlets, and consumer goods shops.',
    sales: 426000,
    target: 300000,
    achievementPct: 142,
    leads: 12458,
    conversions: 1148,
    activeExecutives: 326,
    defaultTargetTemplate: 'Retail Growth Target Q2',
    applicableFor: ['Field Sales', 'Telecalling'],
    allowLeadAssignment: true,
    allowBusinessCreation: true,
    tags: ['Retail', 'B2C', 'High Volume'],
  },
  {
    id: 'cat-2',
    name: 'Food & Restaurant',
    code: 'FOOD',
    parentCategory: '—',
    businessesCount: 1642,
    status: 'Active',
    sortOrder: 2,
    createdOn: '10 May 2025',
    createdBy: 'Priya Sharma',
    iconName: 'Utensils',
    description: 'Restaurants, bakeries, cafes, fast food joints, and cloud kitchens.',
    sales: 384000,
    target: 290000,
    achievementPct: 132,
    leads: 9840,
    conversions: 920,
    activeExecutives: 284,
    defaultTargetTemplate: 'F&B Onboarding Standard',
    applicableFor: ['Field Sales'],
    allowLeadAssignment: true,
    allowBusinessCreation: true,
    tags: ['Dining', 'Food Tech', 'QSR'],
  },
  {
    id: 'cat-3',
    name: 'Healthcare',
    code: 'HEALTH',
    parentCategory: '—',
    businessesCount: 1256,
    status: 'Active',
    sortOrder: 3,
    createdOn: '08 May 2025',
    createdBy: 'Vijay Patel',
    iconName: 'Stethoscope',
    description: 'Hospitals, medical labs, pharmacies, diagnostic centers, and clinics.',
    sales: 312000,
    target: 250000,
    achievementPct: 124,
    leads: 7650,
    conversions: 780,
    activeExecutives: 210,
    defaultTargetTemplate: 'Healthcare Enterprise Target',
    applicableFor: ['Both'],
    allowLeadAssignment: true,
    allowBusinessCreation: true,
    tags: ['Medical', 'Pharma', 'Clinical'],
  },
  {
    id: 'cat-4',
    name: 'Education',
    code: 'EDU',
    parentCategory: '—',
    businessesCount: 1024,
    status: 'Active',
    sortOrder: 4,
    createdOn: '06 May 2025',
    createdBy: 'Neha Verma',
    iconName: 'GraduationCap',
    description: 'Schools, colleges, coaching classes, academies, and vocational centers.',
    sales: 275000,
    target: 240000,
    achievementPct: 114,
    leads: 6420,
    conversions: 610,
    activeExecutives: 175,
    defaultTargetTemplate: 'EdTech Sales Quota',
    applicableFor: ['Telecalling'],
    allowLeadAssignment: true,
    allowBusinessCreation: true,
    tags: ['Education', 'Coaching', 'Institutes'],
  },
  {
    id: 'cat-5',
    name: 'Real Estate',
    code: 'REAL',
    parentCategory: '—',
    businessesCount: 986,
    status: 'Active',
    sortOrder: 5,
    createdOn: '05 May 2025',
    createdBy: 'Rohit Sharma',
    iconName: 'Building2',
    description: 'Property developers, real estate agencies, brokers, and co-working spaces.',
    sales: 450000,
    target: 350000,
    achievementPct: 128,
    leads: 5980,
    conversions: 540,
    activeExecutives: 190,
    defaultTargetTemplate: 'Real Estate Commercial Target',
    applicableFor: ['Both'],
    allowLeadAssignment: true,
    allowBusinessCreation: true,
    tags: ['Property', 'Brokerage', 'High Value'],
  },
  {
    id: 'cat-6',
    name: 'Automotive',
    code: 'AUTO',
    parentCategory: '—',
    businessesCount: 865,
    status: 'Inactive',
    sortOrder: 6,
    createdOn: '03 May 2025',
    createdBy: 'Suresh Patel',
    iconName: 'Car',
    description: 'Auto garages, spare part dealers, car washing centers, and service stations.',
    sales: 198000,
    target: 220000,
    achievementPct: 90,
    leads: 4820,
    conversions: 410,
    activeExecutives: 140,
    defaultTargetTemplate: 'Auto Service Baseline',
    applicableFor: ['Field Sales'],
    allowLeadAssignment: false,
    allowBusinessCreation: true,
    tags: ['Automobile', 'Garages', 'Service'],
  },
  {
    id: 'cat-7',
    name: 'Fashion & Apparel',
    code: 'FASHION',
    parentCategory: 'Retail Business',
    businessesCount: 742,
    status: 'Active',
    sortOrder: 7,
    createdOn: '02 May 2025',
    createdBy: 'Priya Sharma',
    iconName: 'Shirt',
    description: 'Clothing boutiques, footwear stores, fabric retailers, and fashion studios.',
    sales: 240000,
    target: 200000,
    achievementPct: 120,
    leads: 4120,
    conversions: 390,
    activeExecutives: 125,
    tags: ['Apparel', 'Style', 'Retail'],
  },
  {
    id: 'cat-8',
    name: 'IT & Software',
    code: 'IT',
    parentCategory: '—',
    businessesCount: 698,
    status: 'Active',
    sortOrder: 8,
    createdOn: '30 Apr 2025',
    createdBy: 'Vijay Patel',
    iconName: 'Laptop',
    description: 'Software development firms, IT hardware agencies, and digital service providers.',
    sales: 510000,
    target: 400000,
    achievementPct: 127,
    leads: 3950,
    conversions: 480,
    activeExecutives: 165,
    tags: ['Tech', 'SaaS', 'B2B'],
  },
  {
    id: 'cat-9',
    name: 'Home Services',
    code: 'HOME',
    parentCategory: '—',
    businessesCount: 612,
    status: 'Active',
    sortOrder: 9,
    createdOn: '28 Apr 2025',
    createdBy: 'Neha Verma',
    iconName: 'Wrench',
    description: 'Plumbing, electrical services, interior design, pest control, and cleaning.',
    sales: 185000,
    target: 160000,
    achievementPct: 115,
    leads: 3450,
    conversions: 320,
    activeExecutives: 110,
    tags: ['Maintenance', 'Services'],
  },
  {
    id: 'cat-10',
    name: 'Dentist',
    code: 'DENTIST',
    parentCategory: 'Healthcare',
    businessesCount: 485,
    status: 'Active',
    sortOrder: 10,
    createdOn: '26 Apr 2025',
    createdBy: 'Rohit Sharma',
    iconName: 'Sparkles',
    description: 'Dental clinics, orthodontist setups, and specialized dental care centers.',
    sales: 210000,
    target: 180000,
    achievementPct: 116,
    leads: 2980,
    conversions: 290,
    activeExecutives: 95,
    tags: ['Dental', 'Healthcare', 'Doctor'],
  },
  {
    id: 'cat-11',
    name: 'Salon',
    code: 'SALON',
    parentCategory: 'Home Services',
    businessesCount: 520,
    status: 'Active',
    sortOrder: 11,
    createdOn: '25 Apr 2025',
    createdBy: 'Priya Sharma',
    iconName: 'Scissors',
    description: 'Beauty parlors, hair salons, spa centers, and grooming lounges.',
    sales: 235000,
    target: 190000,
    achievementPct: 123,
    leads: 3600,
    conversions: 340,
    activeExecutives: 105,
    tags: ['Beauty', 'Personal Care', 'Spa'],
  },
  {
    id: 'cat-12',
    name: 'Restaurant',
    code: 'RESTAURANT',
    parentCategory: 'Food & Restaurant',
    businessesCount: 890,
    status: 'Active',
    sortOrder: 12,
    createdOn: '24 Apr 2025',
    createdBy: 'Vijay Patel',
    iconName: 'Utensils',
    description: 'Fine dining restaurants, family dhabas, bistros, and banquet halls.',
    sales: 320000,
    target: 250000,
    achievementPct: 128,
    leads: 5400,
    conversions: 510,
    activeExecutives: 160,
    tags: ['Dining', 'Food', 'Hospitality'],
  },
  {
    id: 'cat-13',
    name: 'Gym',
    code: 'GYM',
    parentCategory: 'Healthcare',
    businessesCount: 380,
    status: 'Active',
    sortOrder: 13,
    createdOn: '22 Apr 2025',
    createdBy: 'Suresh Patel',
    iconName: 'Dumbbell',
    description: 'Fitness centers, gyms, crossfit arenas, and yoga studios.',
    sales: 175000,
    target: 150000,
    achievementPct: 116,
    leads: 2600,
    conversions: 230,
    activeExecutives: 85,
    tags: ['Fitness', 'Health', 'Wellness'],
  },
  {
    id: 'cat-14',
    name: 'CA',
    code: 'CA',
    parentCategory: '—',
    businessesCount: 340,
    status: 'Active',
    sortOrder: 14,
    createdOn: '20 Apr 2025',
    createdBy: 'Neha Verma',
    iconName: 'Briefcase',
    description: 'Chartered accountant offices, audit firms, tax consultants, and financial advisors.',
    sales: 290000,
    target: 220000,
    achievementPct: 131,
    leads: 2400,
    conversions: 260,
    activeExecutives: 90,
    tags: ['Tax', 'Accounting', 'Finance'],
  },
  {
    id: 'cat-15',
    name: 'Lawyer',
    code: 'LAWYER',
    parentCategory: '—',
    businessesCount: 290,
    status: 'Active',
    sortOrder: 15,
    createdOn: '18 Apr 2025',
    createdBy: 'Rohit Sharma',
    iconName: 'Scale',
    description: 'Legal firms, advocate chambers, notary services, and legal advisory.',
    sales: 245000,
    target: 200000,
    achievementPct: 122,
    leads: 1950,
    conversions: 210,
    activeExecutives: 75,
    tags: ['Legal', 'Consultancy', 'Law'],
  },
  {
    id: 'cat-16',
    name: 'Clinic',
    code: 'CLINIC',
    parentCategory: 'Healthcare',
    businessesCount: 620,
    status: 'Active',
    sortOrder: 16,
    createdOn: '16 Apr 2025',
    createdBy: 'Priya Sharma',
    iconName: 'Activity',
    description: 'Polyclinics, specialist doctor chambers, and diagnostic consultation clinics.',
    sales: 280000,
    target: 230000,
    achievementPct: 121,
    leads: 4100,
    conversions: 390,
    activeExecutives: 115,
    tags: ['Doctor', 'Healthcare', 'Clinic'],
  },
  {
    id: 'cat-17',
    name: 'Repair Centre',
    code: 'REPAIR',
    parentCategory: 'Home Services',
    businessesCount: 430,
    status: 'Active',
    sortOrder: 17,
    createdOn: '14 Apr 2025',
    createdBy: 'Vijay Patel',
    iconName: 'Wrench',
    description: 'Mobile repair shops, laptop service centers, and home appliance workshops.',
    sales: 165000,
    target: 150000,
    achievementPct: 110,
    leads: 2850,
    conversions: 250,
    activeExecutives: 80,
    tags: ['Repair', 'Tech Service', 'Hardware'],
  },
  {
    id: 'cat-18',
    name: 'Coaching Institute',
    code: 'COACHING',
    parentCategory: 'Education',
    businessesCount: 510,
    status: 'Active',
    sortOrder: 18,
    createdOn: '12 Apr 2025',
    createdBy: 'Neha Verma',
    iconName: 'BookOpen',
    description: 'Competitive exam coaching institutes, tuition centers, and skill academies.',
    sales: 260000,
    target: 210000,
    achievementPct: 123,
    leads: 3700,
    conversions: 330,
    activeExecutives: 105,
    tags: ['Tuition', 'Exams', 'Education'],
  },
];
