import { mockBusinesses } from '../businesses/businessesData';
import { mockTerritoryExecutives } from '../territories/territoriesData';

export interface FollowUpItem {
  id: string;
  followupId: string;
  businessName: string;
  businessAddress: string;
  businessType: string;
  leadId: string;
  contactPerson: string;
  contactRole: string;
  phone: string;
  email: string;
  followupType: 'Demo Follow-up' | 'Quotation Follow-up' | 'Product Info Follow-up' | 'Payment Follow-up';
  assignedToName: string;
  assignedToRole: string;
  assignedToAvatar: string;
  followupDate: string;
  followupTime: string;
  status: 'Completed' | 'Pending' | 'Overdue' | 'Scheduled';
  priority: 'High' | 'Medium' | 'Low';
  leadSource: 'Walk-in' | 'Website' | 'Google Ads' | 'Referral';
  purpose?: string;
  discussionSummary?: string;
  nextSteps?: string;
  outcome?: string;
  result?: string;
  daysOverdue?: number;
  nextFollowupDate?: string;
  nextFollowupType?: string;
  createdOn?: string;
  completedOn?: string;
  attachments?: { name: string; size: string; type: 'PDF' | 'XLSX' | 'DOC' }[];
  notes?: { text: string; date: string; author: string }[];
  timeline?: { title: string; time: string; date: string; author?: string; type: string }[];
}

export const mockFollowUpsList: FollowUpItem[] = [
  {
    id: '1',
    followupId: 'FU-2561',
    businessName: 'Royal Bakers',
    businessAddress: 'Chakala, Andheri East, Mumbai',
    businessType: 'Bakery & Confectionery',
    leadId: 'LD-12561',
    contactPerson: 'Rahul Gupta',
    contactRole: 'Owner',
    phone: '+91 99303 22110',
    email: 'rahul.gupta@bakers.com',
    followupType: 'Demo Follow-up',
    assignedToName: 'Pooja Yadav',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    followupDate: '20 May 2025',
    followupTime: '10:30 AM',
    status: 'Completed',
    priority: 'High',
    leadSource: 'Google Ads',
    purpose: 'Post-demo review and discussion of implementation timeline.',
    discussionSummary: 'Client loved the Live Tracking and Inventory features. Ready to onboard next week.',
    nextSteps: 'Share final agreement and onboard team.',
    outcome: 'Interested',
    result: 'Agreement Sent',
    createdOn: '18 May 2025, 10:00 AM',
    completedOn: '20 May 2025, 11:15 AM',
    attachments: [
      { name: 'Agreement_RoyalBakers.pdf', size: '1.8 MB', type: 'PDF' },
      { name: 'Price_Breakdown.xlsx', size: '240 KB', type: 'XLSX' },
    ],
    notes: [
      { text: 'Customer liked the offer. Confirmed implementation for May 25.', date: '20 May 2025, 11:15 AM', author: 'Pooja Yadav' },
    ],
    timeline: [
      { title: 'Follow-up Created', time: '10:00 AM', date: '18 May 2025', author: 'Pooja Yadav', type: 'created' },
      { title: 'Scheduled', time: '10:30 AM', date: '20 May 2025', type: 'scheduled' },
      { title: 'Follow-up Completed', time: '11:15 AM', date: '20 May 2025', author: 'Pooja Yadav', type: 'completed' },
      { title: 'Outcome: Interested', time: '11:15 AM', date: '20 May 2025', type: 'outcome' },
    ],
  },
  {
    id: '2',
    followupId: 'FU-2560',
    businessName: 'Metro Supermart',
    businessAddress: 'Andheri West, Mumbai',
    businessType: 'Supermarket Chain',
    leadId: 'LD-12560',
    contactPerson: 'Amit Jain',
    contactRole: 'General Manager',
    phone: '+91 98190 77889',
    email: 'amit.jain@metrosuper.com',
    followupType: 'Quotation Follow-up',
    assignedToName: 'Rakesh Patel',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    followupDate: '20 May 2025',
    followupTime: '02:00 PM',
    status: 'Pending',
    priority: 'Medium',
    leadSource: 'Walk-in',
    purpose: 'Review quotation parameters and discuss 15-user license discount.',
    discussionSummary: 'Awaiting internal management sign-off.',
    nextSteps: 'Call back tomorrow afternoon.',
    outcome: 'Pending',
    result: 'Quotation Under Review',
    createdOn: '19 May 2025, 02:00 PM',
  },
  {
    id: '3',
    followupId: 'FU-2559',
    businessName: 'Sharma Medical Store',
    businessAddress: 'Saki Naka, Andheri East, Mumbai',
    businessType: 'Pharmacy & Healthcare',
    leadId: 'LD-12559',
    contactPerson: 'Neha Sharma',
    contactRole: 'Pharmacist',
    phone: '+91 98200 11223',
    email: 'sharma.med@gmail.com',
    followupType: 'Product Info Follow-up',
    assignedToName: 'Neha Sharma',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    followupDate: '21 May 2025',
    followupTime: '10:30 AM',
    status: 'Overdue',
    priority: 'High',
    leadSource: 'Google Ads',
    purpose: 'Clarify batch tracking module capabilities.',
    discussionSummary: 'Customer requires specialized batch expiry notifications.',
    nextSteps: 'Arrange call with tech team.',
    outcome: 'Interested',
    result: 'Tech Call Scheduled',
    daysOverdue: 2,
    createdOn: '17 May 2025, 11:00 AM',
  },
  {
    id: '4',
    followupId: 'FU-2558',
    businessName: 'Patel Electronics',
    businessAddress: 'Jogeshwari West, Mumbai',
    businessType: 'Consumer Electronics',
    leadId: 'LD-12558',
    contactPerson: 'Vijay Patel',
    contactRole: 'Store Manager',
    phone: '+91 97690 44556',
    email: 'vijay@patelelectronics.in',
    followupType: 'Payment Follow-up',
    assignedToName: 'Arjun Mehta',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    followupDate: '21 May 2025',
    followupTime: '03:30 PM',
    status: 'Pending',
    priority: 'High',
    leadSource: 'Referral',
    purpose: 'Collect advance payment for annual subscription.',
    discussionSummary: 'Payment check prepared, pending pickup.',
    nextSteps: 'Visit store for check collection.',
    outcome: 'Pending',
    result: 'Payment Pending',
    createdOn: '18 May 2025, 03:00 PM',
  },
  {
    id: '5',
    followupId: 'FU-2557',
    businessName: 'Om Enterprises',
    businessAddress: 'Oshiwara, Andheri West, Mumbai',
    businessType: 'Hardware & Tools',
    leadId: 'LD-12557',
    contactPerson: 'Mahesh Shah',
    contactRole: 'Proprietor',
    phone: '+91 97020 55678',
    email: 'om.enterprises@gmail.com',
    followupType: 'Demo Follow-up',
    assignedToName: 'Kiran Jadhav',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    followupDate: '22 May 2025',
    followupTime: '11:30 AM',
    status: 'Scheduled',
    priority: 'Medium',
    leadSource: 'Website',
    purpose: 'Demonstrate mobile app offline sync capability.',
    discussionSummary: 'Scheduled hands-on session.',
    nextSteps: 'Conduct offline sync demo.',
    outcome: 'Pending',
    result: 'Demo Scheduled',
    createdOn: '19 May 2025, 09:00 AM',
  },
  {
    id: '6',
    followupId: 'FU-2556',
    businessName: 'Fresh & Green',
    businessAddress: 'Versova, Andheri West, Mumbai - 400061',
    businessType: 'Grocery Store',
    leadId: 'LD-12556',
    contactPerson: 'Ramesh Yadav',
    contactRole: 'Owner',
    phone: '+91 96540 88990',
    email: 'freshgreen@gmail.com',
    followupType: 'Quotation Follow-up',
    assignedToName: 'Pooja Yadav',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    followupDate: '22 May 2025',
    followupTime: '04:00 PM',
    status: 'Pending',
    priority: 'Low',
    leadSource: 'Walk-in',
    purpose: 'To share quotation and discuss requirements',
    discussionSummary: 'Shared detailed quotation. Discussed pricing and delivery. Customer is interested and requested some customizations.',
    nextSteps: 'Follow up after 2 days to confirm requirements and finalize the order.',
    outcome: 'Interested',
    result: 'Quotation Sent',
    daysOverdue: 0,
    nextFollowupDate: '21 May 2025, 12:00 PM',
    nextFollowupType: 'Quotation Follow-up',
    createdOn: '19 May 2025, 12:00 PM',
    completedOn: '19 May 2025, 03:30 PM',
    attachments: [
      { name: 'Quotation_FreshGreen.pdf', size: '245 KB', type: 'PDF' },
      { name: 'Product_Price_List.xlsx', size: '180 KB', type: 'XLSX' },
    ],
    notes: [
      { text: 'Customer liked the offer. Need to confirm customization for packaging. Asked for 2 days time to finalize. Follow up on 21 May 2025.', date: '19 May 2025, 03:30 PM', author: 'Pooja Yadav' },
    ],
    timeline: [
      { title: 'Follow-up Created', time: '12:00 PM', date: '19 May 2025', author: 'Pooja Yadav', type: 'created' },
      { title: 'Scheduled', time: '12:00 PM', date: '19 May 2025', type: 'scheduled' },
      { title: 'Follow-up Completed', time: '03:30 PM', date: '19 May 2025', author: 'Pooja Yadav', type: 'completed' },
      { title: 'Outcome: Interested', time: '03:30 PM', date: '19 May 2025', type: 'outcome' },
      { title: 'Result: Quotation Sent', time: '03:30 PM', date: '19 May 2025', type: 'result' },
    ],
  },
  {
    id: '7',
    followupId: 'FU-2555',
    businessName: 'Anand Fashion',
    businessAddress: 'Andheri East, Mumbai',
    businessType: 'Apparel & Clothing',
    leadId: 'LD-12555',
    contactPerson: 'Anand Verma',
    contactRole: 'Managing Director',
    phone: '+91 98210 66778',
    email: 'anand@anandfashion.com',
    followupType: 'Product Info Follow-up',
    assignedToName: 'Neha Sharma',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    followupDate: '23 May 2025',
    followupTime: '10:00 AM',
    status: 'Scheduled',
    priority: 'Medium',
    leadSource: 'Google Ads',
    purpose: 'Share multi-store inventory sync deck.',
    discussionSummary: 'Planning expansion to 3 new outlets.',
    nextSteps: 'Send proposal for 3 store license package.',
    outcome: 'Pending',
    result: 'Proposal Drafted',
    createdOn: '19 May 2025, 04:00 PM',
  },
  {
    id: '8',
    followupId: 'FU-2554',
    businessName: 'Midas Auto Care',
    businessAddress: 'Andheri East, Mumbai',
    businessType: 'Automobile Service',
    leadId: 'LD-12554',
    contactPerson: 'Imran Shaikh',
    contactRole: 'Service Head',
    phone: '+91 98330 11224',
    email: 'imran@midasauto.com',
    followupType: 'Demo Follow-up',
    assignedToName: 'Rakesh Patel',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    followupDate: '23 May 2025',
    followupTime: '01:00 PM',
    status: 'Completed',
    priority: 'Low',
    leadSource: 'Walk-in',
    purpose: 'Post-pilot feedback session.',
    discussionSummary: 'Team is satisfied with daily service job card feature.',
    nextSteps: 'Activate annual subscription.',
    outcome: 'Interested',
    result: 'Subscription Activated',
    createdOn: '18 May 2025, 11:00 AM',
    completedOn: '23 May 2025, 01:45 PM',
  },
  {
    id: '9',
    followupId: 'FU-2553',
    businessName: 'Sai Enterprises',
    businessAddress: 'Marol, Andheri East, Mumbai',
    businessType: 'Office Supplies',
    leadId: 'LD-12553',
    contactPerson: 'Suresh Patel',
    contactRole: 'Owner',
    phone: '+91 98765 43210',
    email: 'suresh@saienterprises.com',
    followupType: 'Payment Follow-up',
    assignedToName: 'Arjun Mehta',
    assignedToRole: 'Field Executive',
    assignedToAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    followupDate: '24 May 2025',
    followupTime: '03:00 PM',
    status: 'Overdue',
    priority: 'High',
    leadSource: 'Referral',
    purpose: 'Collect payment invoice #2401.',
    discussionSummary: 'Invoice pending for 5 days.',
    nextSteps: 'Escalate to accounts manager.',
    outcome: 'Pending',
    result: 'Payment Overdue',
    daysOverdue: 1,
    createdOn: '16 May 2025, 02:00 PM',
  },
];

export function getFollowUpById(id: string): FollowUpItem | undefined {
  return mockFollowUpsList.find((f) => f.id === id || f.followupId === id);
}
