ALTER TABLE "Territory" ADD COLUMN IF NOT EXISTS "notes" TEXT;

ALTER TABLE "TerritoryTarget"
  ADD COLUMN IF NOT EXISTS "activeBusinessTarget" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "retentionTarget" INTEGER NOT NULL DEFAULT 0;
