import { PermissionScope } from '@prisma/client';

export interface PermissionDefinition {
  code: string;
  scope: PermissionScope;
  domain: string;
  resource: string;
  action: string;
  description: string;
  moduleKey: string;
}

export const PERMISSION_REGISTRY_VERSION = '1.3.0';

export const CRM_PHASE_1_1_PERMISSIONS: PermissionDefinition[] = [
  ...(
    [
      'create',
      'update',
      'delete',
      'assign',
      'access.own',
      'access.tenant',
    ] as const
  ).map((action) => ({
    code: `crm.businesses.${action}`,
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'businesses',
    action,
    description: `Business ${action} access`,
    moduleKey: 'crm_businesses',
  })),
  ...(
    [
      'view',
      'create',
      'update',
      'delete',
      'assign',
      'access.own',
      'access.tenant',
    ] as const
  ).map((action) => ({
    code: `crm.contacts.${action}`,
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'contacts',
    action,
    description: `Contact ${action} access`,
    moduleKey: 'crm_contacts',
  })),
];
export const CRM_PHASE_1_2_PERMISSIONS: PermissionDefinition[] = [
  "view",
  "create",
  "update",
  "delete",
  "assign",
  "convert",
  "import",
  "export",
  "access.own",
  "access.assigned",
  "access.tenant",
].map((action) => ({
  code: "crm.leads." + action,
  scope: PermissionScope.TENANT,
  domain: "crm",
  resource: "leads",
  action,
  description: "Lead " + action + " action",
  moduleKey: "crm_leads",
}));
export const CRM_TERRITORY_PERMISSIONS: PermissionDefinition[] = [
  "view",
  "create",
  "update",
  "delete",
  "assign",
  "access.own",
  "access.tenant",
].map((action) => ({
  code: "crm.territories." + action,
  scope: PermissionScope.TENANT,
  domain: "crm",
  resource: "territories",
  action,
  description: "Territory " + action + " action",
  moduleKey: "crm_territories",
}));
export const PERMISSION_REGISTRY: PermissionDefinition[] = [
  ...CRM_TERRITORY_PERMISSIONS,
  ...CRM_PHASE_1_2_PERMISSIONS,
  ...CRM_PHASE_1_1_PERMISSIONS,
  { code: 'platform.operations.jobs.view', scope: PermissionScope.PLATFORM, domain: 'platform', resource: 'jobs', action: 'view', description: 'View durable job status and attempt history', moduleKey: 'platform_operations' },
  { code: 'platform.operations.jobs.retry', scope: PermissionScope.PLATFORM, domain: 'platform', resource: 'jobs', action: 'retry', description: 'Retry a dead job with a recorded reason', moduleKey: 'platform_operations' },
  { code: 'system.media.view', scope: PermissionScope.TENANT, domain: 'system', resource: 'media', action: 'view', description: 'Download private media in the selected Tenant', moduleKey: 'system' },
  { code: 'system.media.manage', scope: PermissionScope.TENANT, domain: 'system', resource: 'media', action: 'manage', description: 'Upload and delete private media in the selected Tenant', moduleKey: 'system' },
  // ─── PLATFORM SCOPE PERMISSIONS ────────────────────────────────────────────────
  {
    code: 'platform.dashboard.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'dashboard',
    action: 'view',
    description: 'View platform overview dashboard and analytics',
    moduleKey: 'platform_dashboard',
  },
  {
    code: 'platform.tenants.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'tenants',
    action: 'view',
    description: 'List and view platform tenants',
    moduleKey: 'platform_tenants',
  },
  {
    code: 'platform.tenants.create',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'tenants',
    action: 'create',
    description: 'Create new platform tenant',
    moduleKey: 'platform_tenants',
  },
  {
    code: 'platform.tenants.update',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'tenants',
    action: 'update',
    description: 'Update tenant metadata and settings',
    moduleKey: 'platform_tenants',
  },
  {
    code: 'platform.tenants.provision',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'tenants',
    action: 'provision',
    description: 'Provision tenant workspace and resources',
    moduleKey: 'platform_tenants',
  },
  {
    code: 'platform.tenants.suspend',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'tenants',
    action: 'suspend',
    description: 'Suspend or restore platform tenant workspace',
    moduleKey: 'platform_tenants',
  },
  {
    code: 'platform.tenants.members.manage',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'tenants',
    action: 'members_manage',
    description: 'Manage tenant memberships from platform console',
    moduleKey: 'platform_tenants',
  },
  {
    code: 'platform.plans.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'plans',
    action: 'view',
    description: 'View platform pricing plans and versions',
    moduleKey: 'platform_plans',
  },
  {
    code: 'platform.plans.create',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'plans',
    action: 'create',
    description: 'Create draft commercial plans',
    moduleKey: 'platform_plans',
  },
  {
    code: 'platform.plans.update',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'plans',
    action: 'update',
    description: 'Update draft commercial plans',
    moduleKey: 'platform_plans',
  },
  {
    code: 'platform.plans.publish',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'plans',
    action: 'publish',
    description: 'Publish commercial plan version immutably',
    moduleKey: 'platform_plans',
  },
  {
    code: 'platform.plans.archive',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'plans',
    action: 'archive',
    description: 'Archive commercial plan',
    moduleKey: 'platform_plans',
  },
  {
    code: 'platform.modules.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'modules',
    action: 'view',
    description: 'View platform modules and feature registry',
    moduleKey: 'platform_modules',
  },
  {
    code: 'platform.modules.update',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'modules',
    action: 'update',
    description: 'Update platform module metadata and status',
    moduleKey: 'platform_modules',
  },
  {
    code: 'platform.modules.archive',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'modules',
    action: 'archive',
    description: 'Archive platform module',
    moduleKey: 'platform_modules',
  },
  {
    code: 'platform.industries.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'industries',
    action: 'view',
    description: 'View industry templates and defaults',
    moduleKey: 'platform_industries',
  },
  {
    code: 'platform.industries.manage',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'industries',
    action: 'manage',
    description: 'Manage industry drafts, publication and explicit Tenant template assignments',
    moduleKey: 'platform_industries',
  },
  {
    code: 'platform.users.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'users',
    action: 'view',
    description: 'View global platform users',
    moduleKey: 'platform_users',
  },
  {
    code: 'platform.users.manage',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'users',
    action: 'manage',
    description: 'Manage platform user role assignments',
    moduleKey: 'platform_users',
  },
  {
    code: 'platform.roles.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'roles',
    action: 'view',
    description: 'View platform roles and permission grants',
    moduleKey: 'platform_roles',
  },
  {
    code: 'platform.roles.manage',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'roles',
    action: 'manage',
    description: 'Manage platform role permissions',
    moduleKey: 'platform_roles',
  },
  {
    code: 'platform.subscriptions.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'subscriptions',
    action: 'view',
    description: 'View tenant subscriptions and billing state',
    moduleKey: 'platform_subscriptions',
  },
  {
    code: 'platform.subscriptions.manage',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'subscriptions',
    action: 'manage',
    description: 'Manage tenant subscriptions and upgrades',
    moduleKey: 'platform_subscriptions',
  },
  {
    code: 'platform.billing.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'billing',
    action: 'view',
    description: 'View invoices and transaction history',
    moduleKey: 'platform_billing',
  },
  {
    code: 'platform.audit.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'audit',
    action: 'view',
    description: 'View platform system audit logs',
    moduleKey: 'platform_audit',
  },

  // ─── TENANT SCOPE PERMISSIONS ──────────────────────────────────────────────────
  // Shift & Schedule
  {
    code: 'workforce.shifts.view',
    scope: PermissionScope.TENANT,
    domain: 'workforce',
    resource: 'shifts',
    action: 'view',
    description: 'View tenant shift schedules and configurations',
    moduleKey: 'workforce_shifts',
  },
  {
    code: 'workforce.shifts.create',
    scope: PermissionScope.TENANT,
    domain: 'workforce',
    resource: 'shifts',
    action: 'create',
    description: 'Create shift schedule definitions',
    moduleKey: 'workforce_shifts',
  },
  {
    code: 'workforce.shifts.update',
    scope: PermissionScope.TENANT,
    domain: 'workforce',
    resource: 'shifts',
    action: 'update',
    description: 'Update shift schedule parameters',
    moduleKey: 'workforce_shifts',
  },
  {
    code: 'workforce.shifts.assign',
    scope: PermissionScope.TENANT,
    domain: 'workforce',
    resource: 'shifts',
    action: 'assign',
    description: 'Assign shifts to team members',
    moduleKey: 'workforce_shifts',
  },

  // Attendance & Punches
  {
    code: 'attendance.self.punch',
    scope: PermissionScope.TENANT,
    domain: 'attendance',
    resource: 'self',
    action: 'punch',
    description: 'Perform attendance punch-in and punch-out',
    moduleKey: 'attendance_self',
  },
  {
    code: 'attendance.monitoring.view',
    scope: PermissionScope.TENANT,
    domain: 'attendance',
    resource: 'monitoring',
    action: 'view',
    description: 'View team and workspace attendance logs',
    moduleKey: 'attendance_monitoring',
  },

  // Payroll & Payslips
  {
    code: 'payroll.salary_structure.view',
    scope: PermissionScope.TENANT,
    domain: 'payroll',
    resource: 'salary_structure',
    action: 'view',
    description: 'View salary structure details',
    moduleKey: 'payroll_salary',
  },
  {
    code: 'payroll.salary_structure.manage',
    scope: PermissionScope.TENANT,
    domain: 'payroll',
    resource: 'salary_structure',
    action: 'manage',
    description: 'Create and update salary structures',
    moduleKey: 'payroll_salary',
  },
  {
    code: 'payroll.runs.generate',
    scope: PermissionScope.TENANT,
    domain: 'payroll',
    resource: 'runs',
    action: 'generate',
    description: 'Generate monthly payroll runs and payslips',
    moduleKey: 'payroll_runs',
  },
  {
    code: 'payroll.payslips.view',
    scope: PermissionScope.TENANT,
    domain: 'payroll',
    resource: 'payslips',
    action: 'view',
    description: 'View monthly payslips',
    moduleKey: 'payroll_payslips',
  },
  {
    code: 'payroll.payslips.pay',
    scope: PermissionScope.TENANT,
    domain: 'payroll',
    resource: 'payslips',
    action: 'pay',
    description: 'Mark payslips as paid',
    moduleKey: 'payroll_payslips',
  },

  // Fixture UI / Navigation Domain Permissions (for frontend route/sidebar parity)
  {
    code: 'crm.dashboard.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'dashboard',
    action: 'view',
    description: 'View tenant CRM dashboard',
    moduleKey: 'crm_dashboard',
  },
  {
    code: 'crm.leads.manage',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'leads',
    action: 'manage',
    description: 'Manage and reassign leads',
    moduleKey: 'crm_leads',
  },
  {
    code: 'crm.pipeline.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'pipeline',
    action: 'view',
    description: 'View sales pipeline Kanban',
    moduleKey: 'crm_pipeline',
  },
  {
    code: 'crm.businesses.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'businesses',
    action: 'view',
    description: 'View registered businesses',
    moduleKey: 'crm_businesses',
  },
  {
    code: 'crm.targets.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'targets',
    action: 'view',
    description: 'View sales target performance',
    moduleKey: 'crm_targets',
  },
  {
    code: 'crm.incentives.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'incentives',
    action: 'view',
    description: 'View incentives and payout rules',
    moduleKey: 'crm_incentives',
  },
  {
    code: 'crm.performance.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'performance',
    action: 'view',
    description: 'View executive and team ranking performance',
    moduleKey: 'crm_performance',
  },
  {
    code: 'crm.categories.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'categories',
    action: 'view',
    description: 'View business categories',
    moduleKey: 'crm_categories',
  },
  {
    code: 'crm.notifications.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'notifications',
    action: 'view',
    description: 'View workspace notification center',
    moduleKey: 'crm_notifications',
  },
  {
    code: 'crm.notifications.send',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'notifications',
    action: 'create',
    description: 'Create and dispatch notifications and broadcasts',
    moduleKey: 'crm_notifications',
  },
  {
    code: 'crm.notifications.manage',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'notifications',
    action: 'manage',
    description: 'Manage notification templates, device tokens, and settings',
    moduleKey: 'crm_notifications',
  },
  {
    code: 'crm.reports.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'reports',
    action: 'view',
    description: 'View reports and analytics',
    moduleKey: 'crm_reports',
  },
  {
    code: 'crm.customers.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'customers',
    action: 'view',
    description: 'View converted customer accounts',
    moduleKey: 'crm_customers',
  },
  {
    code: 'crm.demos.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'demos',
    action: 'view',
    description: 'View scheduled and completed demos',
    moduleKey: 'crm_demos',
  },
  {
    code: 'crm.followups.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'followups',
    action: 'view',
    description: 'View follow-up tasks and schedule',
    moduleKey: 'crm_followups',
  },
  {
    code: 'crm.visits.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'visits',
    action: 'view',
    description: 'View field visits and GPS exception logs',
    moduleKey: 'crm_visits',
  },
  {
    code: 'crm.map.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'map',
    action: 'view',
    description: 'View live field executive map and tracking',
    moduleKey: 'crm_map',
  },
  {
    code: 'crm.teams.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'teams',
    action: 'view',
    description: 'View sales teams and organizational units',
    moduleKey: 'crm_teams',
  },
  {
    code: 'crm.executives.view',
    scope: PermissionScope.TENANT,
    domain: 'crm',
    resource: 'executives',
    action: 'view',
    description: 'View executive directory and profiles',
    moduleKey: 'crm_executives',
  },
  {
    code: 'platform.masters.view',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'masters',
    action: 'view',
    description: 'View platform Master configuration',
    moduleKey: 'platform_masters',
  },
  {
    code: 'platform.masters.manage',
    scope: PermissionScope.PLATFORM,
    domain: 'platform',
    resource: 'masters',
    action: 'manage',
    description: 'Manage platform Master configuration',
    moduleKey: 'platform_masters',
  },
  {
    code: 'system.masters.manage',
    scope: PermissionScope.TENANT,
    domain: 'system',
    resource: 'masters',
    action: 'manage',
    description: 'Manage permitted Tenant Master labels and overrides',
    moduleKey: 'system_masters',
  },
  {
    code: 'system.masters.view',
    scope: PermissionScope.TENANT,
    domain: 'system',
    resource: 'masters',
    action: 'view',
    description: 'View tenant master records',
    moduleKey: 'system_masters',
  },
  {
    code: 'system.settings.manage',
    scope: PermissionScope.TENANT,
    domain: 'system',
    resource: 'settings',
    action: 'manage',
    description: 'Manage workspace configuration settings',
    moduleKey: 'system_settings',
  },
];

// ─── DEFAULT BUILT-IN ROLE GRANTS ─────────────────────────────────────────────

export const DEFAULT_PLATFORM_ROLE_GRANTS: Record<string, string[]> = {
  PLATFORM_SUPER_ADMIN: PERMISSION_REGISTRY.filter(
    (p) => p.scope === PermissionScope.PLATFORM,
  ).map((p) => p.code),
  PLATFORM_OPERATIONS_ADMIN: [
    'platform.operations.jobs.view',
    'platform.operations.jobs.retry',
    'platform.dashboard.view',
    'platform.tenants.view',
    'platform.tenants.create',
    'platform.tenants.update',
    'platform.tenants.provision',
    'platform.tenants.suspend',
    'platform.tenants.members.manage',
    'platform.plans.view',
    'platform.modules.view',
    'platform.modules.update',
    'platform.industries.view',
    'platform.users.view',
    'platform.roles.view',
    'platform.audit.view',
  ],
  PLATFORM_ONBOARDING: [
    'platform.dashboard.view',
    'platform.tenants.view',
    'platform.tenants.create',
    'platform.tenants.provision',
    'platform.industries.view',
  ],
  PLATFORM_SUPPORT: [
    'platform.dashboard.view',
    'platform.tenants.view',
    'platform.plans.view',
    'platform.modules.view',
    'platform.industries.view',
    'platform.users.view',
    'platform.subscriptions.view',
    'platform.billing.view',
    'platform.audit.view',
  ],
  PLATFORM_BILLING: [
    'platform.dashboard.view',
    'platform.tenants.view',
    'platform.subscriptions.view',
    'platform.subscriptions.manage',
    'platform.billing.view',
  ],
  PLATFORM_AUDITOR: [
    'platform.operations.jobs.view',
    'platform.dashboard.view',
    'platform.tenants.view',
    'platform.audit.view',
  ],
};

export const DEFAULT_TENANT_ROLE_GRANTS: Record<string, string[]> = {
  tenant_admin: PERMISSION_REGISTRY.filter(
    (p) => p.scope === PermissionScope.TENANT,
  ).map((p) => p.code),
  sales_manager: [
    'workforce.shifts.view',
    'workforce.shifts.create',
    'workforce.shifts.update',
    'workforce.shifts.assign',
    'attendance.self.punch',
    'attendance.monitoring.view',
    'crm.dashboard.view',
    'crm.leads.view',
    'crm.leads.create',
    'crm.leads.manage',
    'crm.pipeline.view',
    'crm.businesses.view',
    'crm.territories.view',
    'crm.targets.view',
    'crm.incentives.view',
    'crm.performance.view',
    'crm.categories.view',
    'crm.notifications.view',
    'crm.notifications.send',
    'crm.notifications.manage',
    'crm.reports.view',
    'crm.customers.view',
    'crm.demos.view',
    'crm.followups.view',
    'crm.visits.view',
    'crm.map.view',
    'crm.teams.view',
    'crm.executives.view',
    'system.masters.view',
  ],
  team_leader: [
    'workforce.shifts.view',
    'workforce.shifts.assign',
    'attendance.self.punch',
    'attendance.monitoring.view',
    'crm.dashboard.view',
    'crm.leads.view',
    'crm.leads.create',
    'crm.pipeline.view',
    'crm.businesses.view',
    'crm.territories.view',
    'crm.targets.view',
    'crm.performance.view',
    'crm.categories.view',
    'crm.notifications.view',
    'crm.notifications.send',
    'crm.reports.view',
    'crm.customers.view',
    'crm.demos.view',
    'crm.followups.view',
    'crm.visits.view',
    'crm.map.view',
    'crm.teams.view',
    'crm.executives.view',
    'system.masters.view',
  ],
  field_executive: [
    'attendance.self.punch',
    'crm.dashboard.view',
    'crm.leads.view',
    'crm.leads.create',
    'crm.demos.view',
    'crm.followups.view',
    'crm.visits.view',
  ],
  finance_ops: [
    'payroll.salary_structure.view',
    'payroll.salary_structure.manage',
    'payroll.runs.generate',
    'payroll.payslips.view',
    'payroll.payslips.pay',
    'crm.dashboard.view',
    'crm.incentives.view',
    'crm.reports.view',
    'system.masters.view',
  ],
  support: [
    'workforce.shifts.view',
    'attendance.monitoring.view',
    'crm.dashboard.view',
    'crm.leads.view',
    'crm.businesses.view',
    'crm.notifications.view',
    'system.masters.view',
  ],
};
